name: EssentialsX-CMI-Importer
version: @version@
main: net.essentialsx.cmiimporter.CMIImporter
api-version: "1.13"
depend: [Essentials]
authors: [mdcfe]
description: Imports CMI data into EssentialsX
commands:
  cmi-import:
    description: "Controls CMI data migration."
    usage: "/cmi-import (all|<migrations...>)"